# Site wide configuration
auto: true
title: insupper
description: "this is a population website"
logo: favicon.ico
teaser: 400x250.gif
locale: en_US
pygments: true
url: //insupper.com/main
feed: /atom_1.xml
author_info: <a href="http://xuchanggui.github.com">insupper</a>

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
#permalink: /:title
markdown: kramdown
paginate: 8
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Michael Rose
  web: http://insupper.com
  email: 525081045@qq.com
  twitter: mmistakes
  bio: "Just another boring, tattooed, time traveling designer."
  avatar: hd.jpg # 160x160 px image for author byline
  google:
    plus: +MichaelRoseDesign
    ad-client: ca-pub-7328585512091257
    ad-slot: 3049671934
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
